### ISSUE TITLE
Replace posix close with shutdown

### ISSUE THREAD

**Issue by flouthoc** [flouthoc/envelop.c#2]

**Comment by tpiekarski** [comment]
Just to be sure, I'd like do ask: Do you mean to use [shutdown](https://pubs.opengroup.org/onlinepubs/7908799/xns/shutdown.html) for closing the connection at lines at [452](https://github.com/flouthoc/envelop.c/blob/master/envelop.c#L452) and [456](https://github.com/flouthoc/envelop.c/blob/master/envelop.c#L456)? When yes, so I would like to offer a PR and get a little bit into C development tonight :)

**Comment by flouthoc** [comment]
@tpiekarski Sure !

**Comment by flouthoc** [comment]
@tpiekarski Test by hitting ```127.0.0.1:3000/hello```.

**Comment by tpiekarski** [comment]
Nice getting a little bit back to C and into epoll. 
PR is up and hit 127.0.0.1:3000/hello multiple times for testing :)
